[project]
src = "src"
script = "script"

[networks.battlechain]
url = "https://testnet.battlechain.com"
chain_id = 627
default_account_name = "deployer"
explorer_uri = "https://block-explorer-api.testnet.battlechain.com/api"
explorer_type = "etherscan"
explorer_api_key = "not-required"
